---
development:
  cloud_name: coloradohokie
  api_key: '413862182486864'
  api_secret: 7vkBdJLeOzyUzwEMF242reW2D0c
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: coloradohokie
  api_key: '413862182486864'
  api_secret: 7vkBdJLeOzyUzwEMF242reW2D0c
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: coloradohokie
  api_key: '413862182486864'
  api_secret: 7vkBdJLeOzyUzwEMF242reW2D0c
  enhance_image_tag: true
  static_file_support: false
